version: "3.8"

services:
  app_2fa_checker:
    image: registry.styxx.cloud/2fa-checker:latest
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - PORT=3000
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.app_2fa_checker.rule=Host(`otp.styxx.cloud`)
        - traefik.http.routers.app_2fa_checker.entrypoints=websecure
        - traefik.http.routers.app_2fa_checker.tls.certresolver=letsencryptresolver
        - traefik.http.services.app_2fa_checker.loadbalancer.server.port=3000
        
        # Configurações adicionais para melhor performance
        - traefik.http.routers.app_2fa_checker.middlewares=compress@docker
        
        # Headers de segurança
        - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-For=$$remote_addr
        
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço para auto-build e deploy
  image_builder:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - builder_data:/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      sh -c "
      apk add --no-cache git && \
      while true; do
        echo 'Verificando atualizações no repositório...' && \
        cd /workspace && \
        if [ -d .git ]; then
          git fetch && \
          LOCAL=$$(git rev-parse HEAD) && \
          REMOTE=$$(git rev-parse @{u}) && \
          if [ $$LOCAL != $$REMOTE ]; then
            echo 'Nova versão detectada, fazendo pull...' && \
            git pull && \
            echo 'Construindo nova imagem...' && \
            docker build -t registry.styxx.cloud/2fa-checker:latest . && \
            echo 'Imagem construída com sucesso!' && \
            docker service update --image registry.styxx.cloud/2fa-checker:latest stack_app_2fa_checker || true;
          else
            echo 'Nenhuma atualização disponível.';
          fi;
        else
          echo 'Clonando repositório...' && \
          rm -rf /workspace/* /workspace/.* 2>/dev/null || true && \
          git clone https://github.com/pedrostyxx/2fa-checker.git /workspace && \
          cd /workspace && \
          echo 'Construindo imagem inicial...' && \
          docker build -t registry.styxx.cloud/2fa-checker:latest .;
        fi && \
        echo 'Aguardando 300 segundos antes da próxima verificação...' && \
        sleep 300;
      done
      "
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3

volumes:
  builder_data:

networks:
  network_public:
    external: true