version: "3.7"

services:
  app_2fa_checker:
    build:
      context: https://github.com/pedrostyxx/2fa-checker.git#main
      dockerfile: Dockerfile.simple
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - PORT=80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.app_2fa_checker.rule=Host(`otp.styxx.cloud`)
        - traefik.http.routers.app_2fa_checker.entrypoints=websecure
        - traefik.http.routers.app_2fa_checker.priority=1
        - traefik.http.routers.app_2fa_checker.tls.certresolver=letsencryptresolver
        - traefik.http.routers.app_2fa_checker.service=app_2fa_checker
        - traefik.http.services.app_2fa_checker.loadbalancer.server.port=80
        - traefik.http.services.app_2fa_checker.loadbalancer.passHostHeader=true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  network_public:
    name: network_public
    external: true