version: "3.7"

services:
  app_2fa_checker:
    build:
      context: https://github.com/pedrostyxx/2fa-checker.git#main
      dockerfile: Dockerfile.simple
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - PORT=80
      - NODE_OPTIONS=--max-old-space-size=768
      - NEXT_TELEMETRY_DISABLED=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.app_2fa_checker_simple.rule=Host(`otp.styxx.cloud`)
        - traefik.http.routers.app_2fa_checker_simple.entrypoints=websecure
        - traefik.http.routers.app_2fa_checker_simple.priority=1
        - traefik.http.routers.app_2fa_checker_simple.tls.certresolver=letsencryptresolver
        - traefik.http.routers.app_2fa_checker_simple.service=app_2fa_checker_simple
        - traefik.http.services.app_2fa_checker_simple.loadbalancer.server.port=80
        - traefik.http.services.app_2fa_checker_simple.loadbalancer.passHostHeader=true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  network_public:
    name: network_public
    external: true